language: python
dist: xenial
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install .
  - pip install coveralls

# command to run tests
script:
  - coverage run setup.py test
  - coverage combine

after_success:
  - coveralls