language: python
dist: focal
cache: pip
python:
  - "3.9"
  - "3.10"

# command to install dependencies
install:
  - pip install .
  - pip install coveralls
  - pip install codacy-coverage

# # command to run tests
# script:
#   - coverage run setup.py test
#   - coverage combine
#   - coverage xml

# after_success:
#   - coveralls
#   - python-codacy-coverage -r coverage.xml